"""
API from ST4202
"""

from __future__ import annotations
import enum
from collections.abc import Iterable, Iterator, Mapping
from sublime_types import CommandArgs, CompletionValue, DIP, Kind, Point, Value, Vector
from typing import Callable, Literal, override
from typing_extensions import TypeAlias

class FileTooLargeError(FileNotFoundError): ...

class HoverZone(enum.IntEnum):
    TEXT = 1
    GUTTER = 2
    MARGIN = 3

HOVER_TEXT: int
HOVER_GUTTER: int
HOVER_MARGIN: int

class NewFileFlags(enum.IntFlag):
    NONE = 0
    ENCODED_POSITION = 1
    TRANSIENT = 4
    FORCE_GROUP = 8
    SEMI_TRANSIENT = 16
    ADD_TO_SELECTION = 32
    REPLACE_MRU = 64
    CLEAR_TO_RIGHT = 128
    FORCE_CLONE = 256

ENCODED_POSITION: int
TRANSIENT: int
FORCE_GROUP: int
SEMI_TRANSIENT: int
ADD_TO_SELECTION: int
REPLACE_MRU: int
CLEAR_TO_RIGHT: int
FORCE_CLONE: int

class FindFlags(enum.IntFlag):
    NONE = 0
    LITERAL = 1
    IGNORECASE = 2
    WHOLEWORD = 4
    REVERSE = 8
    WRAP = 16

LITERAL: int
IGNORECASE: int
WHOLEWORD: int
REVERSE: int
WRAP: int

class QuickPanelFlags(enum.IntFlag):
    NONE = 0
    MONOSPACE_FONT = 1
    KEEP_OPEN_ON_FOCUS_LOST = 2
    WANT_EVENT = 4

MONOSPACE_FONT: int
KEEP_OPEN_ON_FOCUS_LOST: int
WANT_EVENT: int

class PopupFlags(enum.IntFlag):
    NONE = 0
    COOPERATE_WITH_AUTO_COMPLETE = 2
    HIDE_ON_MOUSE_MOVE = 4
    HIDE_ON_MOUSE_MOVE_AWAY = 8
    KEEP_ON_SELECTION_MODIFIED = 16
    HIDE_ON_CHARACTER_EVENT = 32

HTML: int
COOPERATE_WITH_AUTO_COMPLETE: int
HIDE_ON_MOUSE_MOVE: int
HIDE_ON_MOUSE_MOVE_AWAY: int
KEEP_ON_SELECTION_MODIFIED: int
HIDE_ON_CHARACTER_EVENT: int

class RegionFlags(enum.IntFlag):
    NONE = 0
    DRAW_EMPTY = 1
    HIDE_ON_MINIMAP = 2
    DRAW_EMPTY_AS_OVERWRITE = 4
    PERSISTENT = 16
    DRAW_NO_FILL = 32
    HIDDEN = 128
    DRAW_NO_OUTLINE = 256
    DRAW_SOLID_UNDERLINE = 512
    DRAW_STIPPLED_UNDERLINE = 1024
    DRAW_SQUIGGLY_UNDERLINE = 2048
    NO_UNDO = 8192

DRAW_EMPTY: int
HIDE_ON_MINIMAP: int
DRAW_EMPTY_AS_OVERWRITE: int
PERSISTENT: int
DRAW_NO_FILL: int
DRAW_OUTLINED = DRAW_NO_FILL
DRAW_NO_OUTLINE: int
DRAW_SOLID_UNDERLINE: int
DRAW_STIPPLED_UNDERLINE: int
DRAW_SQUIGGLY_UNDERLINE: int
NO_UNDO: int
HIDDEN: int

class QueryOperator(enum.IntEnum):
    EQUAL = 0
    NOT_EQUAL = 1
    REGEX_MATCH = 2
    NOT_REGEX_MATCH = 3
    REGEX_CONTAINS = 4
    NOT_REGEX_CONTAINS = 5

OP_EQUAL: int
OP_NOT_EQUAL: int
OP_REGEX_MATCH: int
OP_NOT_REGEX_MATCH: int
OP_REGEX_CONTAINS: int
OP_NOT_REGEX_CONTAINS: int

class PointClassification(enum.IntFlag):
    NONE = 0
    WORD_START = 1
    WORD_END = 2
    PUNCTUATION_START = 4
    PUNCTUATION_END = 8
    SUB_WORD_START = 16
    SUB_WORD_END = 32
    LINE_START = 64
    LINE_END = 128
    EMPTY_LINE = 256

CLASS_WORD_START: int
CLASS_WORD_END: int
CLASS_PUNCTUATION_START: int
CLASS_PUNCTUATION_END: int
CLASS_SUB_WORD_START: int
CLASS_SUB_WORD_END: int
CLASS_LINE_START: int
CLASS_LINE_END: int
CLASS_EMPTY_LINE: int

class AutoCompleteFlags(enum.IntFlag):
    NONE = 0
    INHIBIT_WORD_COMPLETIONS = 8
    INHIBIT_EXPLICIT_COMPLETIONS = 16
    DYNAMIC_COMPLETIONS = 32
    INHIBIT_REORDER = 128

INHIBIT_WORD_COMPLETIONS: int
INHIBIT_EXPLICIT_COMPLETIONS: int
DYNAMIC_COMPLETIONS: int
INHIBIT_REORDER: int

class CompletionItemFlags(enum.IntFlag):
    NONE = 0
    KEEP_PREFIX = 1

COMPLETION_FLAG_KEEP_PREFIX: int

class DialogResult(enum.IntEnum):
    CANCEL = 0
    YES = 1
    NO = 2

DIALOG_CANCEL: int
DIALOG_YES: int
DIALOG_NO: int

class UIElement(enum.IntEnum):
    SIDE_BAR = 1
    MINIMAP = 2
    TABS = 4
    STATUS_BAR = 8
    MENU = 16
    OPEN_FILES = 32

class PhantomLayout(enum.IntEnum):
    INLINE = 0
    BELOW = 1
    BLOCK = 2

LAYOUT_INLINE: int
LAYOUT_BELOW: int
LAYOUT_BLOCK: int

class KindId(enum.IntEnum):
    AMBIGUOUS = 0
    KEYWORD = 1
    TYPE = 2
    FUNCTION = 3
    NAMESPACE = 4
    NAVIGATION = 5
    MARKUP = 6
    VARIABLE = 7
    SNIPPET = 8
    COLOR_REDISH = 9
    COLOR_ORANGISH = 10
    COLOR_YELLOWISH = 11
    COLOR_GREENISH = 12
    COLOR_CYANISH = 13
    COLOR_BLUISH = 14
    COLOR_PURPLISH = 15
    COLOR_PINKISH = 16
    COLOR_DARK = 17
    COLOR_LIGHT = 18

KIND_ID_AMBIGUOUS: int
KIND_ID_KEYWORD: int
KIND_ID_TYPE: int
KIND_ID_FUNCTION: int
KIND_ID_NAMESPACE: int
KIND_ID_NAVIGATION: int
KIND_ID_MARKUP: int
KIND_ID_VARIABLE: int
KIND_ID_SNIPPET: int
KIND_ID_COLOR_REDISH: int
KIND_ID_COLOR_ORANGISH: int
KIND_ID_COLOR_YELLOWISH: int
KIND_ID_COLOR_GREENISH: int
KIND_ID_COLOR_CYANISH: int
KIND_ID_COLOR_BLUISH: int
KIND_ID_COLOR_PURPLISH: int
KIND_ID_COLOR_PINKISH: int
KIND_ID_COLOR_DARK: int
KIND_ID_COLOR_LIGHT: int
KIND_AMBIGUOUS: Kind
KIND_KEYWORD: Kind
KIND_TYPE: Kind
KIND_FUNCTION: Kind
KIND_NAMESPACE: Kind
KIND_NAVIGATION: Kind
KIND_MARKUP: Kind
KIND_VARIABLE: Kind
KIND_SNIPPET: Kind

class SymbolSource(enum.IntEnum):
    ANY = 0
    INDEX = 1
    OPEN_FILES = 2

SYMBOL_SOURCE_ANY: int
SYMBOL_SOURCE_INDEX: int
SYMBOL_SOURCE_OPEN_FILES: int

class SymbolType(enum.IntEnum):
    ANY = 0
    DEFINITION = 1
    REFERENCE = 2

SYMBOL_TYPE_ANY: int
SYMBOL_TYPE_DEFINITION: int
SYMBOL_TYPE_REFERENCE: int

class CompletionFormat(enum.IntEnum):
    TEXT = 0
    SNIPPET = 1
    COMMAND = 2

COMPLETION_FORMAT_TEXT: int
COMPLETION_FORMAT_SNIPPET: int
COMPLETION_FORMAT_COMMAND: int

def version() -> str: ...
def platform() -> Literal['osx', 'linux', 'windows']: ...
def arch() -> Literal['x32', 'x64', 'arm64']: ...
def channel() -> Literal['dev', 'stable']: ...
def executable_path() -> str: ...
def executable_hash() -> tuple[str, str, str]: ...
def packages_path() -> str: ...
def installed_packages_path() -> str: ...
def cache_path() -> str: ...
def lib_path() -> str: ...
def status_message(msg: str) -> None: ...
def error_message(msg: str) -> None: ...
def message_dialog(msg: str) -> None: ...
def ok_cancel_dialog(msg: str, ok_title: str = '', title: str = '') -> bool: ...
def yes_no_cancel_dialog(msg: str, yes_title: str = '', no_title: str = '', title: str = '') -> DialogResult: ...
def open_dialog(callback: Callable[[str | list[str] | None], None], file_types: list[tuple[str, list[str]]] = [], directory: str | None = None, multi_select: bool = False, allow_folders: bool = False) -> None: ...
def save_dialog(callback: Callable[[str | None], None], file_types: list[tuple[str, list[str]]] = [], directory: str | None = None, name: str | None = None, extension: str | None = None) -> None: ...
def select_folder_dialog(callback: Callable[[str | list[str] | None], None], directory: str | None = None, multi_select: bool = False) -> None: ...
def choose_font_dialog(callback: Callable[[Value], None], default: dict[str, Value] | None = None) -> None: ...
def run_command(cmd: str, args: CommandArgs = None) -> None: ...
def format_command(cmd: str, args: CommandArgs = None) -> str: ...
def html_format_command(cmd: str, args: CommandArgs = None) -> str: ...
def command_url(cmd: str, args: CommandArgs = None) -> str: ...
def get_clipboard_async(callback: Callable[[str], None], size_limit: int = 16777216) -> None: ...
def get_clipboard(size_limit: int = 16777216) -> str: ...
def set_clipboard(text: str) -> None: ...
def log_commands(flag: bool | None = None) -> None: ...
def get_log_commands() -> bool: ...
def log_input(flag: bool | None = None) -> None: ...
def get_log_input() -> bool: ...
def log_fps(flag: bool | None = None) -> None: ...
def get_log_fps() -> bool: ...
def log_result_regex(flag: bool | None = None) -> None: ...
def get_log_result_regex() -> bool: ...
def log_indexing(flag: bool | None = None) -> None: ...
def get_log_indexing() -> bool: ...
def log_build_systems(flag: bool | None = None) -> None: ...
def get_log_build_systems() -> bool: ...
def log_control_tree(flag: bool | None = None) -> None: ...
def get_log_control_tree() -> bool: ...
def ui_info() -> dict[str, Value]: ...
def score_selector(scope_name: str, selector: str) -> int: ...
def load_resource(name: str, max_size: int = ...) -> str: ...
def load_binary_resource(name: str, max_size: int = ...) -> bytes: ...
def find_resources(pattern: str) -> list[str]: ...
def encode_value(value: Value, pretty: bool = False, update_text: str | None = None) -> str: ...
def decode_value(data: str) -> Value: ...
def expand_variables(value: Value, variables: dict[str, str]) -> Value: ...
def load_settings(base_name: str) -> Settings: ...
def save_settings(base_name: str) -> None: ...
def set_timeout(callback: Callable[[], None], delay: int = 0) -> None: ...
def set_timeout_async(callback: Callable[[], None], delay: int = 0) -> None: ...
def active_window() -> Window: ...
def windows() -> list[Window]: ...
def get_macro() -> list[dict[str, str | CommandArgs]]: ...
def project_history() -> list[str]: ...
def folder_history() -> list[str]: ...

class Window:
    window_id: int
    settings_object: Settings | None
    template_settings_object: Settings | None
    def __init__(self, id: int) -> None: ...
    @override
    def __hash__(self) -> int: ...
    @override
    def __eq__(self, other: object) -> bool: ...
    def __bool__(self) -> bool: ...
    def id(self) -> int: ...
    def is_valid(self) -> bool: ...
    def hwnd(self) -> int: ...
    def active_sheet(self) -> Sheet | None: ...
    def active_view(self) -> View | None: ...
    def new_html_sheet(self, name: str, contents: str, flags: NewFileFlags = ..., group: int = -1) -> Sheet: ...
    def run_command(self, cmd: str, args: CommandArgs = None) -> None: ...
    def new_file(self, flags: NewFileFlags = ..., syntax: str = '') -> View: ...
    def open_file(self, fname: str, flags: NewFileFlags = ..., group: int = -1) -> View: ...
    def find_open_file(self, fname: str, group: int = -1) -> View | None: ...
    def file_history(self) -> list[str]: ...
    def num_groups(self) -> int: ...
    def active_group(self) -> int: ...
    def focus_group(self, idx: int) -> None: ...
    def focus_sheet(self, sheet: Sheet) -> None: ...
    def focus_view(self, view: View) -> None: ...
    def select_sheets(self, sheets: list[Sheet]) -> None: ...
    def bring_to_front(self) -> None: ...
    def get_sheet_index(self, sheet: Sheet) -> tuple[int, int]: ...
    def get_view_index(self, view: View) -> tuple[int, int]: ...
    def set_sheet_index(self, sheet: Sheet, group: int, index: int) -> None: ...
    def set_view_index(self, view: View, group: int, index: int) -> None: ...
    def move_sheets_to_group(self, sheets: list[Sheet], group: int, insertion_idx: int = -1, select: bool = True) -> None: ...
    def sheets(self) -> list[Sheet]: ...
    def views(self, *, include_transient: bool = False) -> list[View]: ...
    def selected_sheets(self) -> list[Sheet]: ...
    def selected_sheets_in_group(self, group: int) -> list[Sheet]: ...
    def active_sheet_in_group(self, group: int) -> Sheet | None: ...
    def active_view_in_group(self, group: int) -> View | None: ...
    def sheets_in_group(self, group: int) -> list[Sheet]: ...
    def views_in_group(self, group: int) -> list[View]: ...
    def num_sheets_in_group(self, group: int) -> int: ...
    def num_views_in_group(self, group: int) -> int: ...
    def transient_sheet_in_group(self, group: int) -> Sheet | None: ...
    def transient_view_in_group(self, group: int) -> View | None: ...
    def promote_sheet(self, sheet: Sheet) -> None: ...
    def layout(self) -> dict[str, Value]: ...
    def get_layout(self) -> dict[str, Value]: ...
    def set_layout(self, layout: dict[str, Value]) -> None: ...
    def create_output_panel(self, name: str, unlisted: bool = False) -> View: ...
    def find_output_panel(self, name: str) -> View | None: ...
    def destroy_output_panel(self, name: str) -> None: ...
    def create_io_panel(self, name: str, on_input: Callable[[str], None], unlisted: bool = False) -> tuple[View, View]: ...
    def find_io_panel(self, name: str) -> tuple[View | None, View | None]: ...
    def active_panel(self) -> str | None: ...
    def panels(self) -> list[str]: ...
    def get_output_panel(self, name: str) -> View: ...
    def show_input_panel(self, caption: str, initial_text: str, on_done: Callable[[str], None] | None, on_change: Callable[[str], None] | None, on_cancel: Callable[[], None] | None) -> View: ...
    def show_quick_panel(self, items: list[str] | list[list[str]] | list[QuickPanelItem], on_select: Callable[[int], None], flags: QuickPanelFlags = ..., selected_index: int = -1, on_highlight: Callable[[int], None] | None = None, placeholder: str | None = None) -> None: ...
    def is_sidebar_visible(self) -> bool: ...
    def set_sidebar_visible(self, flag: bool, animate: bool = True) -> None: ...
    def is_minimap_visible(self) -> bool: ...
    def set_minimap_visible(self, flag: bool) -> None: ...
    def is_status_bar_visible(self) -> bool: ...
    def set_status_bar_visible(self, flag: bool) -> None: ...
    def get_tabs_visible(self) -> bool: ...
    def set_tabs_visible(self, flag: bool) -> None: ...
    def is_menu_visible(self) -> bool: ...
    def set_menu_visible(self, flag: bool) -> None: ...
    def folders(self) -> list[str]: ...
    def project_file_name(self) -> str | None: ...
    def workspace_file_name(self) -> str | None: ...
    def project_data(self) -> dict[str, Value] | None: ...
    def set_project_data(self, data: dict[str, Value]) -> None: ...
    def settings(self) -> Settings: ...
    def template_settings(self) -> Settings: ...
    def symbol_locations(self, sym: str, source: SymbolSource = ..., type: SymbolType = ..., kind_id: KindId = ..., kind_letter: str = '') -> list[SymbolLocation]: ...
    def lookup_symbol_in_index(self, symbol: str) -> list[SymbolLocation]: ...
    def lookup_symbol_in_open_files(self, symbol: str) -> list[SymbolLocation]: ...
    def lookup_references_in_index(self, symbol: str) -> list[SymbolLocation]: ...
    def lookup_references_in_open_files(self, symbol: str) -> list[SymbolLocation]: ...
    def extract_variables(self) -> dict[str, str]: ...
    def status_message(self, msg: str) -> None: ...

class Edit:
    edit_token: int
    def __init__(self, token: int) -> None: ...

class Region:
    a: Point
    b: Point
    xpos: DIP
    def __init__(self, a: Point, b: Point | None = None, xpos: DIP = -1) -> None: ...
    def __iter__(self) -> Iterator[int]: ...
    def __len__(self) -> int: ...
    @override
    def __eq__(self, rhs: object) -> bool: ...
    def __lt__(self, rhs: Region) -> bool: ...
    def __contains__(self, v: Region | Point) -> bool: ...
    def to_tuple(self) -> tuple[Point, Point]: ...
    def empty(self) -> bool: ...
    def begin(self) -> Point: ...
    def end(self) -> Point: ...
    def size(self) -> int: ...
    def contains(self, x: Point) -> bool: ...
    def cover(self, region: Region) -> Region: ...
    def intersection(self, region: Region) -> Region: ...
    def intersects(self, region: Region) -> bool: ...

class HistoricPosition:
    pt: Point
    row: int
    col: int
    col_utf16: int
    col_utf8: int
    def __init__(self, pt: Point, row: int, col: int, col_utf16: int, col_utf8: int) -> None: ...

Str: TypeAlias = str

class TextChange:
    a: HistoricPosition
    b: HistoricPosition
    len_utf16: int
    len_utf8: int
    str: Str
    def __init__(self, pa: HistoricPosition, pb: HistoricPosition, len_utf16: int, len_utf8: int, s: Str) -> None: ...

class Selection:
    view_id: int
    def __init__(self, id: int) -> None: ...
    def __iter__(self) -> Iterator[Region]: ...
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> Region: ...
    def __delitem__(self, index: int) -> None: ...
    @override
    def __eq__(self, rhs: object) -> bool: ...
    def __lt__(self, rhs: Selection | None) -> bool: ...
    def __bool__(self) -> bool: ...
    def is_valid(self) -> bool: ...
    def clear(self) -> None: ...
    def add(self, x: Region | Point) -> None: ...
    def add_all(self, regions: Iterable[Region | Point]) -> None: ...
    def subtract(self, region: Region) -> None: ...
    def contains(self, region: Region) -> bool: ...
    def has_empty_region(self) -> bool: ...
    def has_non_empty_region(self) -> bool: ...
    def has_multiple_non_empty_regions(self) -> bool: ...

def make_sheet(sheet_id: int) -> Sheet: ...

class Sheet:
    sheet_id: int
    def __init__(self, id: int) -> None: ...
    @override
    def __hash__(self) -> int: ...
    @override
    def __eq__(self, other: object) -> bool: ...
    def id(self) -> int: ...
    def window(self) -> Window | None: ...
    def view(self) -> View | None: ...
    def name(self) -> str | None: ...
    def set_name(self, name: str) -> None: ...
    def file_name(self) -> str | None: ...
    def is_semi_transient(self) -> bool: ...
    def is_transient(self) -> bool: ...
    def is_selected(self) -> bool: ...
    def group(self) -> int | None: ...
    def close(self, on_close: Callable[[bool], None] = ...) -> None: ...

class TextSheet(Sheet): ...
class ImageSheet(Sheet): ...

class HtmlSheet(Sheet):
    def set_contents(self, contents: str) -> None: ...

class ContextStackFrame:
    context_name: str
    source_file: str
    source_location: tuple[int, int]
    def __init__(self, context_name: str, source_file: str, source_location: tuple[int, int]) -> None: ...

class View:
    view_id: int
    selection: Selection
    settings_object: Settings | None
    def __init__(self, id: int) -> None: ...
    def __len__(self) -> int: ...
    @override
    def __hash__(self) -> int: ...
    @override
    def __eq__(self, other: object) -> bool: ...
    def __bool__(self) -> bool: ...
    def id(self) -> int: ...
    def buffer_id(self) -> int: ...
    def buffer(self) -> Buffer: ...
    def sheet_id(self) -> int: ...
    def sheet(self) -> Sheet | None: ...
    def element(self) -> str | None: ...
    def is_valid(self) -> bool: ...
    def is_primary(self) -> bool: ...
    def window(self) -> Window | None: ...
    def clones(self) -> list[View]: ...
    def file_name(self) -> str | None: ...
    def close(self, on_close: Callable[[bool], None] = ...) -> bool: ...
    def retarget(self, new_fname: str) -> None: ...
    def name(self) -> str: ...
    def set_name(self, name: str) -> None: ...
    def reset_reference_document(self) -> None: ...
    def set_reference_document(self, reference: str) -> None: ...
    def is_loading(self) -> bool: ...
    def is_dirty(self) -> bool: ...
    def is_read_only(self) -> bool: ...
    def set_read_only(self, read_only: bool) -> None: ...
    def is_scratch(self) -> bool: ...
    def set_scratch(self, scratch: bool) -> None: ...
    def encoding(self) -> str: ...
    def set_encoding(self, encoding_name: str) -> None: ...
    def line_endings(self) -> str: ...
    def set_line_endings(self, line_ending_name: str) -> None: ...
    def size(self) -> int: ...
    def begin_edit(self, edit_token: int, cmd: str, args: CommandArgs = None) -> Edit: ...
    def end_edit(self, edit: Edit) -> None: ...
    def is_in_edit(self) -> bool: ...
    def insert(self, edit: Edit, pt: Point, text: str) -> int: ...
    def erase(self, edit: Edit, region: Region) -> None: ...
    def replace(self, edit: Edit, region: Region, text: str) -> None: ...
    def change_count(self) -> int: ...
    def change_id(self) -> tuple[int, int, int]: ...
    def transform_region_from(self, region: Region, change_id: tuple[int, int, int]) -> Region: ...
    def run_command(self, cmd: str, args: CommandArgs = None) -> None: ...
    def sel(self) -> Selection: ...
    def substr(self, x: Region | Point) -> str: ...
    def find(self, pattern: str, start_pt: Point, flags: FindFlags = ...) -> Region: ...
    def find_all(self, pattern: str, flags: FindFlags = ..., fmt: str | None = None, extractions: list[str] | None = None, within: Region | list[Region] | None = None) -> list[Region]: ...
    def settings(self) -> Settings: ...
    def meta_info(self, key: str, pt: Point) -> Value: ...
    def extract_tokens_with_scopes(self, region: Region) -> list[tuple[Region, str]]: ...
    def extract_scope(self, pt: Point) -> Region: ...
    def expand_to_scope(self, pt: Point, selector: str) -> Region | None: ...
    def scope_name(self, pt: Point) -> str: ...
    def context_backtrace(self, pt: Point) -> list[ContextStackFrame]: ...
    def match_selector(self, pt: Point, selector: str) -> bool: ...
    def score_selector(self, pt: Point, selector: str) -> int: ...
    def find_by_selector(self, selector: str) -> list[Region]: ...
    def style(self) -> dict[str, str]: ...
    def style_for_scope(self, scope: str) -> dict[str, Value]: ...
    def indented_region(self, pt: Point) -> Region: ...
    def indentation_level(self, pt: Point) -> int: ...
    def has_non_empty_selection_region(self) -> bool: ...
    def lines(self, region: Region) -> list[Region]: ...
    def split_by_newlines(self, region: Region) -> list[Region]: ...
    def line(self, x: Region | Point) -> Region: ...
    def full_line(self, x: Region | Point) -> Region: ...
    def word(self, x: Region | Point) -> Region: ...
    def classify(self, pt: Point) -> PointClassification: ...
    def find_by_class(self, pt: Point, forward: bool, classes: PointClassification, separators: str = '', sub_word_separators: str = '') -> Point: ...
    def expand_by_class(self, x: Region | Point, classes: PointClassification, separators: str = '', sub_word_separators: str = '') -> Region: ...
    def rowcol(self, tp: Point) -> tuple[int, int]: ...
    def rowcol_utf8(self, tp: Point) -> tuple[int, int]: ...
    def rowcol_utf16(self, tp: Point) -> tuple[int, int]: ...
    def text_point(self, row: int, col: int, *, clamp_column: bool = False) -> Point: ...
    def text_point_utf8(self, row: int, col: int, *, clamp_column: bool = False) -> Point: ...
    def text_point_utf16(self, row: int, col: int, *, clamp_column: bool = False) -> Point: ...
    def utf8_code_units(self, tp: Point | None = None) -> int: ...
    def utf16_code_units(self, tp: Point | None = None) -> int: ...
    def visible_region(self) -> Region: ...
    def show(self, location: Region | Selection | Point, show_surrounds: bool = True, keep_to_left: bool = False, animate: bool = True) -> None: ...
    def show_at_center(self, location: Region | Point, animate: bool = True) -> None: ...
    def viewport_position(self) -> Vector: ...
    def set_viewport_position(self, xy: Vector, animate: bool = True) -> None: ...
    def viewport_extent(self) -> Vector: ...
    def layout_extent(self) -> Vector: ...
    def text_to_layout(self, tp: Point) -> Vector: ...
    def text_to_window(self, tp: Point) -> Vector: ...
    def layout_to_text(self, xy: Vector) -> Point: ...
    def layout_to_window(self, xy: Vector) -> Vector: ...
    def window_to_layout(self, xy: Vector) -> Vector: ...
    def window_to_text(self, xy: Vector) -> Point: ...
    def line_height(self) -> DIP: ...
    def em_width(self) -> DIP: ...
    def is_folded(self, region: Region) -> bool: ...
    def folded_regions(self) -> list[Region]: ...
    def fold(self, x: Region | list[Region]) -> bool: ...
    def unfold(self, x: Region | list[Region]) -> list[Region]: ...
    def add_regions(self, key: str, regions: list[Region], scope: str = '', icon: str = '', flags: RegionFlags = ..., annotations: list[str] = [], annotation_color: str = '', on_navigate: Callable[[str], None] | None = None, on_close: Callable[[], None] | None = None) -> None: ...
    def get_regions(self, key: str) -> list[Region]: ...
    def erase_regions(self, key: str) -> None: ...
    def add_phantom(self, key: str, region: Region, content: str, layout: PhantomLayout, on_navigate: Callable[[str], None] | None = None) -> int: ...
    def erase_phantoms(self, key: str) -> None: ...
    def erase_phantom_by_id(self, pid: int) -> None: ...
    def query_phantom(self, pid: int) -> list[Region]: ...
    def query_phantoms(self, pids: list[int]) -> list[Region]: ...
    def assign_syntax(self, syntax: str | Syntax) -> None: ...
    def set_syntax_file(self, syntax_file: str) -> None: ...
    def syntax(self) -> Syntax | None: ...
    def symbols(self) -> list[tuple[Region, str]]: ...
    def get_symbols(self) -> list[tuple[Region, str]]: ...
    def indexed_symbols(self) -> list[tuple[Region, str]]: ...
    def indexed_references(self) -> list[tuple[Region, str]]: ...
    def symbol_regions(self) -> list[SymbolRegion]: ...
    def indexed_symbol_regions(self, type: SymbolType = ...) -> list[SymbolRegion]: ...
    def set_status(self, key: str, value: str) -> None: ...
    def get_status(self, key: str) -> str: ...
    def erase_status(self, key: str) -> None: ...
    def extract_completions(self, prefix: str, tp: Point = -1) -> list[str]: ...
    def find_all_results(self) -> list[tuple[str, int, int]]: ...
    def find_all_results_with_text(self) -> list[tuple[str, int, int, str]]: ...
    def command_history(self, index: int, modifying_only: bool = False) -> tuple[str, CommandArgs, int]: ...
    def overwrite_status(self) -> bool: ...
    def set_overwrite_status(self, value: bool) -> None: ...
    def show_popup_menu(self, items: list[str], on_done: Callable[[int], None], flags: int = 0) -> None: ...
    def show_popup(self, content: str, flags: PopupFlags = ..., location: Point = -1, max_width: DIP = 320, max_height: DIP = 240, on_navigate: Callable[[str], None] | None = None, on_hide: Callable[[], None] | None = None) -> None: ...
    def update_popup(self, content: str) -> None: ...
    def is_popup_visible(self) -> bool: ...
    def hide_popup(self) -> None: ...
    def is_auto_complete_visible(self) -> bool: ...
    def preserve_auto_complete_on_focus_lost(self) -> None: ...
    def export_to_html(self, regions: Region | list[Region] | None = None, minihtml: bool = False, enclosing_tags: bool = False, font_size: bool = True, font_family: bool = True) -> str: ...
    def clear_undo_stack(self) -> None: ...

class Buffer:
    buffer_id: int
    def __init__(self, id: int) -> None: ...
    @override
    def __hash__(self) -> int: ...
    @override
    def __eq__(self, other: object) -> bool: ...
    def id(self) -> int: ...
    def file_name(self) -> str | None: ...
    def views(self) -> list[View]: ...
    def primary_view(self) -> View: ...

class Settings:
    settings_id: int
    def __init__(self, id: int) -> None: ...
    def __getitem__(self, key: str) -> Value: ...
    def __setitem__(self, key: str, value: Value) -> None: ...
    def __delitem__(self, key: str) -> None: ...
    def __contains__(self, key: str) -> bool: ...
    def to_dict(self) -> dict[str, Value]: ...
    def setdefault(self, key: str, value: Value) -> Value: ...
    def update(self, other: Mapping[str, Value] | Iterable[tuple[str, Value]] | None = None, /, **kwargs: object) -> None: ...
    def get(self, key: str, default: Value = None) -> Value: ...
    def has(self, key: str) -> bool: ...
    def set(self, key: str, value: Value) -> None: ...
    def erase(self, key: str) -> None: ...
    def add_on_change(self, tag: str, callback: Callable[[], None]) -> None: ...
    def clear_on_change(self, tag: str) -> None: ...

class Phantom:
    region: Region
    content: str
    layout: PhantomLayout
    on_navigate: Callable[[str], None] | None
    id: int | None
    def __init__(self, region: Region, content: str, layout: PhantomLayout, on_navigate: Callable[[str], None] | None = None) -> None: ...
    @override
    def __eq__(self, rhs: object) -> bool: ...
    def to_tuple(self) -> tuple[tuple[Point, Point], str, PhantomLayout, Callable[[str], None] | None]: ...

class PhantomSet:
    view: View
    key: str
    phantoms: list[Phantom]
    def __init__(self, view: View, key: str = '') -> None: ...
    def __del__(self) -> None: ...
    def update(self, phantoms: Iterable[Phantom]) -> None: ...

class Html:
    data: str
    def __init__(self, data: str) -> None: ...

class CompletionList:
    completions: list[CompletionValue] | None
    flags: AutoCompleteFlags
    def __init__(self, completions: list[CompletionValue] | None = None, flags: AutoCompleteFlags = ...) -> None: ...
    def set_completions(self, completions: list[CompletionValue], flags: AutoCompleteFlags = ...) -> None: ...

class CompletionItem:
    trigger: str
    annotation: str
    completion: str
    completion_format: CompletionFormat
    kind: Kind
    details: str
    flags: CompletionItemFlags
    def __init__(self, trigger: str, annotation: str = '', completion: str = '', completion_format: CompletionFormat = ..., kind: Kind = ..., details: str = '', flags: CompletionItemFlags = ...) -> None: ...
    @override
    def __eq__(self, rhs: object) -> bool: ...
    @classmethod
    def snippet_completion(cls, trigger: str, snippet: str, annotation: str = '', kind: Kind = ..., details: str = '') -> CompletionItem: ...
    @classmethod
    def command_completion(cls, trigger: str, command: str, args: CommandArgs = None, annotation: str = '', kind: Kind = ..., details: str = '') -> CompletionItem: ...

def list_syntaxes() -> list[Syntax]: ...
def syntax_from_path(path: str) -> Syntax | None: ...
def find_syntax_by_name(name: str) -> list[Syntax]: ...
def find_syntax_by_scope(scope: str) -> list[Syntax]: ...
def find_syntax_for_file(path: str, first_line: str = '') -> Syntax | None: ...

class Syntax:
    path: str
    name: str
    hidden: bool
    scope: str
    def __init__(self, path: str, name: str, hidden: bool, scope: str) -> None: ...
    @override
    def __eq__(self, other: object) -> bool: ...
    @override
    def __hash__(self) -> int: ...

class QuickPanelItem:
    trigger: str
    details: str | list[str] | tuple[str]
    annotation: str
    kind: Kind
    def __init__(self, trigger: str, details: str | list[str] | tuple[str] = '', annotation: str = '', kind: Kind = ...) -> None: ...

class ListInputItem:
    text: str
    value: object
    details: str | list[str] | tuple[str]
    annotation: str
    kind: Kind
    def __init__(self, text: str, value: object, details: str | list[str] | tuple[str] = '', annotation: str = '', kind: Kind = ...) -> None: ...

class SymbolRegion:
    name: str
    region: Region
    syntax: str
    type: SymbolType
    kind: Kind
    def __init__(self, name: str, region: Region, syntax: str, type: SymbolType, kind: Kind) -> None: ...

class SymbolLocation:
    path: str
    display_name: str
    row: int
    col: int
    syntax: str
    type: SymbolType
    kind: Kind
    def __init__(self, path: str, display_name: str, row: int, col: int, syntax: str, type: SymbolType, kind: Kind) -> None: ...
    def path_encoded_position(self) -> str: ...
