"""
API from ST4202
"""

import sublime
from sublime_types import CommandArgs, CompletionValue, Event, Point, Value

class CommandInputHandler:
    def name(self) -> str: ...
    def placeholder(self) -> str: ...
    def initial_text(self) -> str: ...
    def initial_selection(self) -> list[tuple[int, int]]: ...
    def preview(self, text: str) -> str | sublime.Html: ...
    def validate(self, text: str, event: Event | None = None) -> bool: ...
    def cancel(self) -> None: ...
    def confirm(self, text: str, event: Event | None = None) -> None: ...
    def next_input(self, args: CommandArgs) -> CommandInputHandler | None: ...
    def want_event(self) -> bool: ...

class BackInputHandler(CommandInputHandler): ...

class TextInputHandler(CommandInputHandler):
    def description(self, text: str) -> str: ...

class ListInputHandler(CommandInputHandler):
    def list_items(self) -> list[str] | tuple[list[str], int] | list[tuple[str, Value]] | tuple[list[tuple[str, Value]], int] | list[sublime.ListInputItem] | tuple[list[sublime.ListInputItem], int]: ...
    def description(self, value: object, text: str) -> str: ...

class Command:
    @classmethod
    def name(cls) -> str: ...
    def is_enabled(self) -> bool: ...
    def is_visible(self) -> bool: ...
    def is_checked(self) -> bool: ...
    def description(self) -> str: ...
    def filter_args(self, args: CommandArgs) -> CommandArgs: ...
    def want_event(self) -> bool: ...
    def input(self, args: CommandArgs) -> CommandInputHandler | None: ...
    def input_description(self) -> str: ...

class ApplicationCommand(Command):
    def run(self, **kwargs: Value) -> None: ...

class WindowCommand(Command):
    window: sublime.Window
    def __init__(self, window: sublime.Window) -> None: ...
    def run(self, **kwargs: Value) -> None: ...

class TextCommand(Command):
    view: sublime.View
    def __init__(self, view: sublime.View) -> None: ...
    def run(self, edit: sublime.Edit, **kwargs: Value) -> None: ...

class EventListener:
    def on_init(self, view: sublime.View) -> None: ...
    def on_new(self, view: sublime.View) -> None: ...
    def on_new_async(self, view: sublime.View) -> None: ...
    def on_clone(self, view: sublime.View) -> None: ...
    def on_clone_async(self, view: sublime.View) -> None: ...
    def on_load(self, view: sublime.View) -> None: ...
    def on_load_async(self, view: sublime.View) -> None: ...
    def on_pre_close(self, view: sublime.View) -> None: ...
    def on_close(self, view: sublime.View) -> None: ...
    def on_pre_save(self, view: sublime.View) -> None: ...
    def on_pre_save_async(self, view: sublime.View) -> None: ...
    def on_post_save(self, view: sublime.View) -> None: ...
    def on_post_save_async(self, view: sublime.View) -> None: ...
    def on_modified(self, view: sublime.View) -> None: ...
    def on_modified_async(self, view: sublime.View) -> None: ...
    def on_selection_modified(self, view: sublime.View) -> None: ...
    def on_selection_modified_async(self, view: sublime.View) -> None: ...
    def on_activated(self, view: sublime.View) -> None: ...
    def on_activated_async(self, view: sublime.View) -> None: ...
    def on_deactivated(self, view: sublime.View) -> None: ...
    def on_deactivated_async(self, view: sublime.View) -> None: ...
    def on_hover(self, view: sublime.View, point: Point, hover_zone: sublime.HoverZone) -> None: ...
    def on_query_context(self, view: sublime.View, key: str, operator: int, operand: str, match_all: bool) -> bool | None: ...
    def on_query_completions(self, view: sublime.View, prefix: str, locations: list[Point]) -> (None | list[CompletionValue] | tuple[list[CompletionValue], sublime.AutoCompleteFlags] | sublime.CompletionList): ...
    def on_text_command(self, view: sublime.View, command_name: str, args: CommandArgs) -> tuple[str, Value] | None: ...
    def on_post_text_command(self, view: sublime.View, command_name: str, args: CommandArgs) -> None: ...
    def on_window_command(self, view: sublime.Window, command_name: str, args: CommandArgs) -> tuple[str, Value] | None: ...
    def on_post_window_command(self, view: sublime.Window, command_name: str, args: CommandArgs) -> None: ...
    def on_new_buffer(self, buffer: sublime.Buffer) -> None: ...
    def on_new_buffer_async(self, buffer: sublime.Buffer) -> None: ...
    def on_associate_buffer(self, buffer: sublime.Buffer) -> None: ...
    def on_associate_buffer_async(self, buffer: sublime.Buffer) -> None: ...
    def on_close_buffer(self, buffer: sublime.Buffer) -> None: ...
    def on_close_buffer_async(self, buffer: sublime.Buffer) -> None: ...
    def on_new_project(self, window: sublime.Window) -> None: ...
    def on_new_project_async(self, window: sublime.Window) -> None: ...
    def on_load_project(self, window: sublime.Window) -> None: ...
    def on_load_project_async(self, window: sublime.Window) -> None: ...
    def on_pre_save_project(self, window: sublime.Window) -> None: ...
    def on_post_save_project(self, window: sublime.Window) -> None: ...
    def on_post_save_project_async(self, window: sublime.Window) -> None: ...
    def on_pre_close_project(self, window: sublime.Window) -> None: ...
    def on_new_window(self, window: sublime.Window) -> None: ...
    def on_new_window_async(self, window: sublime.Window) -> None: ...
    def on_pre_close_window(self, window: sublime.Window) -> None: ...
    def on_exit(self) -> None: ...

class ViewEventListener:
    view: sublime.View
    @classmethod
    def is_applicable(cls, settings: sublime.Settings) -> bool: ...
    @classmethod
    def applies_to_primary_view_only(cls) -> bool: ...
    def on_load(self) -> None: ...
    def on_load_async(self) -> None: ...
    def on_pre_close(self) -> None: ...
    def on_close(self) -> None: ...
    def on_pre_save(self) -> None: ...
    def on_pre_save_async(self) -> None: ...
    def on_post_save(self) -> None: ...
    def on_post_save_async(self) -> None: ...
    def on_modified(self) -> None: ...
    def on_modified_async(self) -> None: ...
    def on_selection_modified(self) -> None: ...
    def on_selection_modified_async(self) -> None: ...
    def on_activated_modified(self) -> None: ...
    def on_activated_modified_async(self) -> None: ...
    def on_deactivated_modified(self) -> None: ...
    def on_deactivated_modified_async(self) -> None: ...
    def on_hover(self, point: Point, hover_zone: sublime.HoverZone) -> None: ...
    def on_query_context(self, key: str, operator: int, operand: str, match_all: bool) -> bool | None: ...
    def on_query_completions(self, prefix: str, locations: list[Point]) -> (None | list[CompletionValue] | tuple[list[CompletionValue], sublime.AutoCompleteFlags] | sublime.CompletionList): ...
    def on_text_command(self, command_name: str, args: CommandArgs) -> tuple[str, Value] | None: ...
    def on_post_text_command(self, command_name: str, args: CommandArgs) -> None: ...

class TextChangeListener:
    buffer: sublime.Buffer | None
    @classmethod
    def is_applicable(cls, buffer: sublime.Buffer) -> None: ...
    def __init__(self) -> None: ...
    def detach(self) -> None: ...
    def attach(self, buffer: sublime.Buffer) -> None: ...
    def is_attached(self) -> bool: ...
    def on_text_changed(self, changes: list[sublime.TextChange]) -> None: ...
    def on_text_changed_async(self, changes: list[sublime.TextChange]) -> None: ...
    def on_revert(self) -> None: ...
    def on_revert_async(self) -> None: ...
    def on_reload(self) -> None: ...
    def on_reload_async(self) -> None: ...
